openapi: 3.0.3
info:
  title: Public Photo Voting System API
  description: |
    API specification for the public photo voting system. This system allows anonymous visitors
    to rate contest photos using thumbs up/down voting, with navigation between rated and unrated photos.

    **Key Features:**
    - Cookie-based anonymous user identification (fwb_id)
    - Thumbs up (+1) / thumbs down (-1) voting
    - Vote changes supported (recalculates rating)
    - Sequential navigation (next unrated, previous rated)
    - Progress tracking (X of Y photos rated)
    - Rate limiting (60 votes per hour per IP)

  version: 1.0.0
  contact:
    name: Fotowettbewerb Bernbeuren
    url: https://fotowettbewerb-bernbeuren.de

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://fotowettbewerb-bernbeuren.de
    description: Production server

tags:
  - name: Gallery
    description: Public photo gallery and voting endpoints

paths:
  /gallery:
    get:
      summary: Display voting gallery
      description: |
        Returns the public voting gallery page. Automatically displays the first unrated photo
        for the visitor (identified by fwb_id cookie). If no unrated photos exist, shows the
        first photo chronologically with completion message.

        **Behavior:**
        - First-time visitor: Generates fwb_id cookie, shows first unrated photo
        - Returning visitor: Shows first unrated photo (continues voting progress)
        - All photos voted: Shows first photo with completion message

      operationId: galleryIndex
      tags:
        - Gallery
      parameters:
        - in: cookie
          name: fwb_id
          description: Anonymous visitor identifier (auto-generated if missing)
          required: false
          schema:
            type: string
            format: uuid
            example: 550e8400-e29b-41d4-a716-446655440000
      responses:
        '200':
          description: Successful response with gallery page
          headers:
            Set-Cookie:
              description: fwb_id cookie (set if not present)
              schema:
                type: string
                example: fwb_id=550e8400-e29b-41d4-a716-446655440000; Max-Age=31536000; Path=/; HttpOnly; Secure; SameSite=Lax
          content:
            text/html:
              schema:
                type: string
                description: Inertia.js rendered React page (gallery.tsx)
              example: |
                <!-- Inertia page with props:
                  {
                    "photo": {...},
                    "nextPhoto": {...},
                    "previousPhoto": null,
                    "progress": {"rated": 0, "total": 25},
                    "fwbId": "550e8400-e29b-41d4-a716-446655440000"
                  }
                -->
        '404':
          description: No approved photos available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: No photos available for voting yet.

  /gallery/{photoSubmissionId}:
    get:
      summary: Display specific photo
      description: |
        Returns the voting page for a specific photo. Includes navigation data (next unrated,
        previous rated) and visitor's current vote status.

        **Authorization:** None required (public endpoint)
        **Rate Limiting:** None on GET requests

      operationId: galleryShow
      tags:
        - Gallery
      parameters:
        - in: path
          name: photoSubmissionId
          required: true
          description: Photo submission ID
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 42
        - in: cookie
          name: fwb_id
          description: Anonymous visitor identifier
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response with photo page
          headers:
            Set-Cookie:
              description: fwb_id cookie (set if not present)
              schema:
                type: string
          content:
            text/html:
              schema:
                type: string
                description: Inertia.js rendered React page (gallery.tsx)
        '404':
          description: Photo not found or not approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Photo not found.

  /gallery/{photoSubmissionId}/vote:
    post:
      summary: Submit or update vote
      description: |
        Submits a new vote or updates an existing vote for a photo. Vote changes are supported
        and will recalculate the photo's rating accordingly.

        **Vote Logic:**
        - New thumbs up: rating +1
        - New thumbs down: rating -1
        - Change up→down: rating -2
        - Change down→up: rating +2
        - Same vote again: no change

        **Authorization:** None required (anonymous via cookie)
        **Rate Limiting:** 60 requests per hour per IP address

      operationId: galleryVote
      tags:
        - Gallery
      parameters:
        - in: path
          name: photoSubmissionId
          required: true
          description: Photo submission ID
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 42
        - in: cookie
          name: fwb_id
          description: Anonymous visitor identifier (required, auto-generated if missing)
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VoteRequest'
      responses:
        '302':
          description: Vote recorded successfully, redirect to photo page
          headers:
            Location:
              description: Redirect to photo page
              schema:
                type: string
                example: /gallery/42
            Set-Cookie:
              description: fwb_id cookie (set if not present)
              schema:
                type: string
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                message: The given data was invalid.
                errors:
                  vote_type:
                    - The vote type field is required.
        '429':
          description: Rate limit exceeded
          headers:
            Retry-After:
              description: Seconds until rate limit resets
              schema:
                type: integer
                example: 3600
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Too Many Attempts.
        '404':
          description: Photo not found or not approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Photo not found.
        '500':
          description: Server error (transaction failed, database error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: An error occurred while processing your vote.

components:
  schemas:
    Photo:
      type: object
      description: Photo submission data for voting
      required:
        - id
        - image_url
        - rate
        - user_vote
      properties:
        id:
          type: integer
          format: int64
          description: Photo submission ID
          example: 42
        image_url:
          type: string
          format: uri
          description: Public URL to photo image
          example: /storage/photos/abc123.jpg
        title:
          type: string
          nullable: true
          description: Optional photo title
          example: Sunset over Bernbeuren
        rate:
          type: integer
          format: int32
          minimum: 0
          description: Cumulative rating (sum of all votes, minimum 0)
          example: 15
        user_vote:
          type: string
          nullable: true
          enum: [up, down, null]
          description: Current visitor's vote status (null if not voted)
          example: up
        created_at:
          type: string
          format: date-time
          description: Photo submission timestamp
          example: 2025-11-10T14:30:00Z

    NavigationData:
      type: object
      description: Navigation data for photo gallery
      required:
        - next_photo
        - previous_photo
      properties:
        next_photo:
          type: object
          nullable: true
          description: Next unrated photo (null if none)
          properties:
            id:
              type: integer
              format: int64
              example: 43
        previous_photo:
          type: object
          nullable: true
          description: Previous rated photo (null if none)
          properties:
            id:
              type: integer
              format: int64
              example: 41

    ProgressData:
      type: object
      description: Voting progress tracking
      required:
        - rated
        - total
      properties:
        rated:
          type: integer
          format: int32
          minimum: 0
          description: Number of photos visitor has rated
          example: 10
        total:
          type: integer
          format: int32
          minimum: 0
          description: Total number of approved photos
          example: 25

    VoteRequest:
      type: object
      description: Vote submission payload
      required:
        - vote_type
      properties:
        vote_type:
          type: boolean
          description: Vote type (true = thumbs up, false = thumbs down)
          example: true

    Error:
      type: object
      description: Generic error response
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: An error occurred.

    ValidationError:
      type: object
      description: Validation error response
      required:
        - message
        - errors
      properties:
        message:
          type: string
          description: General error message
          example: The given data was invalid.
        errors:
          type: object
          description: Field-specific error messages
          additionalProperties:
            type: array
            items:
              type: string
          example:
            vote_type:
              - The vote type field is required.

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: fwb_id
      description: |
        Anonymous visitor identifier stored in HTTP-only cookie. Auto-generated on first request
        if missing. Used to track votes and prevent duplicates.

        **Properties:**
        - Format: UUID v4
        - Expiration: 1 year
        - Flags: HttpOnly, Secure (production), SameSite=Lax

security:
  - cookieAuth: []

x-rate-limits:
  voting:
    description: Rate limiting for vote submissions
    limit: 60
    period: 1 hour
    scope: per IP address
    response: 429 Too Many Attempts
